### ISSUE TITLE
dateTime#dateDescriptive not localized

### ISSUE THREAD

**Issue by alfsoft** [PoomSmart/MoreSiri#1]
When I say, for example, "Weather" in my language, Siri tells me: "Сейчас в период с < dateTime#dateDescriptive not localized in ru_RU > по < dateTime#dateDescriptive not localized in ru_RU > погода не очень хорошая... температура упала до -13°С, будет снег".
That can be translated as "The weather from < dateTime#dateDescriptive not localized > to < dateTime#dateDescriptive not localized > is not so good". As you can see, Siri cannot read dates in Russian.

**Comment by PoomSmart** [comment]
It might be due to some changes in iOS 8.3 that I haven't discovered yet.

**Comment by alfsoft** [comment]
Seems that it was a server related issue. Now everything works ok. Sorry.
