### ISSUE TITLE
[REQUEST] Could we add Hindi support?

### ISSUE THREAD

**Issue by SalmanBurhan** [PoomSmart/MoreSiri#2]
Would it be possible to add support for Hindi. I've been hoping for this for quite some time now. If it is possible could you add it? I know for a fact that iOS allows you to set Hindi as a default language for the system, they have a keyboard for it as well. If it's any help the localization code for Hindi is "hi-IN", which is Hindi-India.

**Comment by PoomSmart** [comment]
Hindi isn't supported by Apple server. I just tested it with my iPod.

**Comment by SalmanBurhan** [comment]
Aww. Thanks for trying. It's nice to know you care :) thigh I'm not sure why apple isn't working in this. a good portion of their customers are  Indian. a good amount.

**Comment by SalmanBurhan** [comment]
you can close this issue now since it was not possible...

**Comment by SalmanBurhan** [comment]
Thanks :)
